### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by iusyk** [xen-troops/meta-xt-prod-aos#123]
If start build according to the instruction, the following error happens at the start of the build
ERROR: ParseError at /mnt/work/build/meta-xt-images/recipes-domu/domu-image-android/domu-image-android.bb:5: Could not include required file inc/xt_shared_env.inc

corresponded manifest of meta-xt-images must be have a reference at the revision  29904d57ee5660d7beebdff4bb470b7a4d488219

**Comment by rshym** [comment]
This issue is fixed by PR https://github.com/xen-troops/meta-xt-images/pull/207
I have sent request to merge three times already.

**Comment by rshym** [comment]
Fix for issue is merged.
Fixed in xen-troops/meta-xt-images#207
